name: Notify of CFE issue created
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'code freeze exception'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup WooCommerce Monorepo
        uses: ./.github/actions/setup-woocommerce-monorepo

      - name: Add comment
        run: 'pnpm utils slack message ${{ secrets.SLACK_TOKEN }} "CFE issue created! The thing: ${{ toJson(github) }}" general'
