name: Notify of CFE issue created
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'code freeze exception'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Verify if user is authorized
        id: verify_user
        uses: actions/github-script@v6
        with:
          script: |
            const key = 'valid_user';
            const value = false;
            fs.appendFileSync(process.env.GITHUB_OUTPUT, `${key}=${value}\n`)
      - name: Send Slack message
        if: ${{ steps.verify_user.outputs.valid_user == 'true' }}
        uses: archive/github-actions-slack@d9dae40827adf93bddf939db6552d1e392259d7d
        id: notify-slack
        with:
            slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
            slack-channel: general
            slack-text: |
                CFE created!
                ${{ toJson(github) }}
            slack-optional-unfurl_links: false
            slack-optional-unfurl_media: false
      - name: Close the issue
        if: ${{ steps.verify_user.outputs.valid_user != 'true' }}
        run: gh issue close --comment "Closing issue. **Only WooCommerce employees can open CFEs.**" "${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

