name: Notify of CFE issue created
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'code freeze exception'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Send Slack message
        uses: actions/github-script@v6
        with:
          script: |
            const http = new HttpClient();
            const body = "CFE received: " + toJson(github);
            const headers = { 'authorization': 'Bearer ' + ${{ secrets.SLACK_TOKEN }} };
            const response = await http.request('POST', 'https://slack.com/api/chat.postMessage', body, headers);

            const success = response.message.statusCode && response.message.statusCode < 400;
            if(!success) {
              core.setFailed(`Request failed with status code ${response.message.statusCode}.`);
            }
