name: Notify of CFE issue created
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'code freeze exception'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Send Slack message
        uses: archive/github-actions-slack@d9dae40827adf93bddf939db6552d1e392259d7d
        id: notify-slack
        with:
            slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
            slack-channel: general
            slack-text: |
                CFE created!
                ${{ toJson(github) }}
            slack-optional-unfurl_links: false
            slack-optional-unfurl_media: false
  
